apiVersion: apps/v1
kind: Deployment
metadata:
  name: vminsert
  namespace: monitoring
  labels:
    app: vminsert
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vminsert
  template:
    metadata:
      labels:
        app: vminsert
    spec:
      containers:
        - name: vminsert
          image: victoriametrics/vminsert
          args: ["-storageNode", "vmstorage:8400"]
          ports:
            - containerPort: 8480
              name: insert
              protocol: TCP