apiVersion: v1
kind: Pod
metadata:
  name: vminsert
  labels:
    app: vminsert
spec:
  containers:
  - image: victoriametrics/vminsert
    name: vminsert
    args: ["-storageNode", "vmstorage:8400"]
    ports:
    - containerPort: 8480
      name: insert
      protocol: TCP