apiVersion: v1
kind: Pod
metadata:
  name: vmselect
  labels:
    app: vmselect
spec:
  containers:
  - image: victoriametrics/vmselect
    name: vmselect
    args: ["-storageNode", "vmstorage:8400"]
    ports:
    - containerPort: 8481
      name: select
      protocol: TCP