apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmselect
  labels:
    app: vmselect
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vmselect
  template:
    metadata:
      labels:
        app: vmselect
    spec:
      containers:
        - name: vmselect
          image: victoriametrics/vmselect
          args: ["-storageNode", "vmstorage:8401"]
          ports:
            - containerPort: 8481
              name: select
              protocol: TCP