apiVersion: v1
kind: PersistentVolume
metadata:
  name: vmstorage
  namespace: monitoring
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/vmstorage