apiVersion: v1
kind: Pod
metadata:
  name: vmstorage
  labels:
    app: vmstorage
spec:
  containers:
  - image: victoriametrics/vmstorage
    name: vmstorage
    ports:
    - containerPort: 8400
      name: insert
      protocol: TCP
    - containerPort: 8401
      name: select
      protocol: TCP