apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vmstorage
  namespace: monitoring
spec:
  resources:
    requests:
      storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""