apiVersion: v1
kind: Service
metadata:
  name: vmstorage
spec:
  type: NodePort
  ports:
  - port: 8400
    name: vminsert
  - port: 8401
    name: vmselect
  - port: 8482
    name: vmstorage
  selector:
    app: vmstorage